name: Deploy Lambda Function

on:
  push:
    branches:
      - aws-prod
  pull_request:
    branches:
      - aws-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp api/proxy.js deployment/index.js
        cd deployment
        zip -r ../lambda-deployment.zip .
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name figma-proxy \
          --zip-file fileb://lambda-deployment.zip